/*
 * Definitions shared between client and server.
 * @author MrAnkso
 */

// Map patrol zones
BLUFOR_ZONE_SOUTH_WEST     = 0;
INSURGENTS_ZONE_SOUTH_WEST = 1;
INSURGENTS_ZONE_SOUTH_EAST = 2;
INSURGENTS_ZONE_MOUNTAIN   = 3;
OPFOR_ZONE_SOUTH_EAST      = 4;
OPFOR_ZONE_NORTH_EAST      = 5;
BLUFOR_ZONE_NORTH_WEST     = 6;
MAX_PATROL_ZONES           = 7;

// Map dungeons/complexes
DUNGEON_LA_RIVIERE        = 0;
DUNGEON_SOUTH_EAST_HARBOR = 1;
DUNGEON_HOUDAN            = 2;
DUNGEON_LA_PESSAGNE       = 3;
DUNGEON_MILITARY_HARBOR   = 4;
DUNGEON_FUEL_DEPOT        = 5;
DUNGEON_LA_TRINITE        = 6;
DUNGEON_MILITARY_AIRFIELD = 7;
DUNGEON_USS_FREEDOM       = 8;
DUNGEON_GOISSE            = 9;
DUNGEON_OLD_MILITARY_BASE = 10;
DUNGEON_CAPTURED_AIRFIELD = 11;
MAX_DUNGEONS = 12;
